root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/frameval-engine ./cmd/server"
bin = "./tmp/frameval-engine"
include_ext = ["go"]
exclude_dir = ["tmp"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
