// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grader.proto

package graderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_grader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GradeRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TranscriptJson string                 `protobuf:"bytes,2,opt,name=transcript_json,json=transcriptJson,proto3" json:"transcript_json,omitempty"`
	OutputFiles    []*OutputFile          `protobuf:"bytes,3,rep,name=output_files,json=outputFiles,proto3" json:"output_files,omitempty"`
	FilesystemDiff string                 `protobuf:"bytes,4,opt,name=filesystem_diff,json=filesystemDiff,proto3" json:"filesystem_diff,omitempty"`
	Task           *TaskSpec              `protobuf:"bytes,5,opt,name=task,proto3" json:"task,omitempty"`
	Artifact       *ArtifactSpec          `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	JudgeConfig    *JudgeConfig           `protobuf:"bytes,7,opt,name=judge_config,json=judgeConfig,proto3" json:"judge_config,omitempty"`
	// Engine-side test results from the actual sandbox (which has the test
	// files). When present, the grader skips its own subprocess-based test
	// runner — that one operates on output_files in a tempdir and reports
	// 0/N for brownfield tasks whose test files aren't in output_files.
	// Without this, the judge sees test_pass_rate=0 even when tests passed,
	// and hallucinates "tests failed" rationales.
	VerifiedTestResults *VerifiedTestResults `protobuf:"bytes,8,opt,name=verified_test_results,json=verifiedTestResults,proto3" json:"verified_test_results,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GradeRunRequest) Reset() {
	*x = GradeRunRequest{}
	mi := &file_grader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRunRequest) ProtoMessage() {}

func (x *GradeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRunRequest.ProtoReflect.Descriptor instead.
func (*GradeRunRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{2}
}

func (x *GradeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GradeRunRequest) GetTranscriptJson() string {
	if x != nil {
		return x.TranscriptJson
	}
	return ""
}

func (x *GradeRunRequest) GetOutputFiles() []*OutputFile {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

func (x *GradeRunRequest) GetFilesystemDiff() string {
	if x != nil {
		return x.FilesystemDiff
	}
	return ""
}

func (x *GradeRunRequest) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GradeRunRequest) GetArtifact() *ArtifactSpec {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GradeRunRequest) GetJudgeConfig() *JudgeConfig {
	if x != nil {
		return x.JudgeConfig
	}
	return nil
}

func (x *GradeRunRequest) GetVerifiedTestResults() *VerifiedTestResults {
	if x != nil {
		return x.VerifiedTestResults
	}
	return nil
}

type VerifiedTestResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassCount     int32                  `protobuf:"varint,1,opt,name=pass_count,json=passCount,proto3" json:"pass_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,2,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	Results       []*VerifiedTestResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifiedTestResults) Reset() {
	*x = VerifiedTestResults{}
	mi := &file_grader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedTestResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedTestResults) ProtoMessage() {}

func (x *VerifiedTestResults) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedTestResults.ProtoReflect.Descriptor instead.
func (*VerifiedTestResults) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{3}
}

func (x *VerifiedTestResults) GetPassCount() int32 {
	if x != nil {
		return x.PassCount
	}
	return 0
}

func (x *VerifiedTestResults) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *VerifiedTestResults) GetResults() []*VerifiedTestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type VerifiedTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifiedTestResult) Reset() {
	*x = VerifiedTestResult{}
	mi := &file_grader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedTestResult) ProtoMessage() {}

func (x *VerifiedTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedTestResult.ProtoReflect.Descriptor instead.
func (*VerifiedTestResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{4}
}

func (x *VerifiedTestResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifiedTestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *VerifiedTestResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type OutputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputFile) Reset() {
	*x = OutputFile{}
	mi := &file_grader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFile) ProtoMessage() {}

func (x *OutputFile) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFile.ProtoReflect.Descriptor instead.
func (*OutputFile) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{5}
}

func (x *OutputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutputFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type TaskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CodebaseType  string                 `protobuf:"bytes,3,opt,name=codebase_type,json=codebaseType,proto3" json:"codebase_type,omitempty"`
	TestCases     []*TestCase            `protobuf:"bytes,4,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	SetupScript   string                 `protobuf:"bytes,5,opt,name=setup_script,json=setupScript,proto3" json:"setup_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_grader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{6}
}

func (x *TaskSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskSpec) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskSpec) GetCodebaseType() string {
	if x != nil {
		return x.CodebaseType
	}
	return ""
}

func (x *TaskSpec) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

func (x *TaskSpec) GetSetupScript() string {
	if x != nil {
		return x.SetupScript
	}
	return ""
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExpectedResult string                 `protobuf:"bytes,3,opt,name=expected_result,json=expectedResult,proto3" json:"expected_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_grader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{7}
}

func (x *TestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestCase) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TestCase) GetExpectedResult() string {
	if x != nil {
		return x.ExpectedResult
	}
	return ""
}

type ArtifactSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSpec) Reset() {
	*x = ArtifactSpec{}
	mi := &file_grader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSpec) ProtoMessage() {}

func (x *ArtifactSpec) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSpec.ProtoReflect.Descriptor instead.
func (*ArtifactSpec) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{8}
}

func (x *ArtifactSpec) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArtifactSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DimensionRubric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionRubric) Reset() {
	*x = DimensionRubric{}
	mi := &file_grader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionRubric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionRubric) ProtoMessage() {}

func (x *DimensionRubric) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionRubric.ProtoReflect.Descriptor instead.
func (*DimensionRubric) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{9}
}

func (x *DimensionRubric) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DimensionRubric) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type JudgeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Rubric        []*RubricDimension     `protobuf:"bytes,4,rep,name=rubric,proto3" json:"rubric,omitempty"`
	JudgeRounds   int32                  `protobuf:"varint,5,opt,name=judge_rounds,json=judgeRounds,proto3" json:"judge_rounds,omitempty"`
	Rubrics       []*DimensionRubric     `protobuf:"bytes,6,rep,name=rubrics,proto3" json:"rubrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeConfig) Reset() {
	*x = JudgeConfig{}
	mi := &file_grader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeConfig) ProtoMessage() {}

func (x *JudgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeConfig.ProtoReflect.Descriptor instead.
func (*JudgeConfig) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{10}
}

func (x *JudgeConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *JudgeConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *JudgeConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *JudgeConfig) GetRubric() []*RubricDimension {
	if x != nil {
		return x.Rubric
	}
	return nil
}

func (x *JudgeConfig) GetJudgeRounds() int32 {
	if x != nil {
		return x.JudgeRounds
	}
	return 0
}

func (x *JudgeConfig) GetRubrics() []*DimensionRubric {
	if x != nil {
		return x.Rubrics
	}
	return nil
}

type RubricDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Criteria      string                 `protobuf:"bytes,2,opt,name=criteria,proto3" json:"criteria,omitempty"`
	MinScore      int32                  `protobuf:"varint,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RubricDimension) Reset() {
	*x = RubricDimension{}
	mi := &file_grader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RubricDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RubricDimension) ProtoMessage() {}

func (x *RubricDimension) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RubricDimension.ProtoReflect.Descriptor instead.
func (*RubricDimension) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{11}
}

func (x *RubricDimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RubricDimension) GetCriteria() string {
	if x != nil {
		return x.Criteria
	}
	return ""
}

func (x *RubricDimension) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *RubricDimension) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type GradeRunResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           *CodeGradeResult       `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Process        *ProcessGradeResult    `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	Judge          *JudgeGradeResult      `protobuf:"bytes,3,opt,name=judge,proto3" json:"judge,omitempty"`
	Adherence      *SpecAdherenceResult   `protobuf:"bytes,4,opt,name=adherence,proto3" json:"adherence,omitempty"`
	CompositeScore float32                `protobuf:"fixed32,5,opt,name=composite_score,json=compositeScore,proto3" json:"composite_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GradeRunResponse) Reset() {
	*x = GradeRunResponse{}
	mi := &file_grader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRunResponse) ProtoMessage() {}

func (x *GradeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRunResponse.ProtoReflect.Descriptor instead.
func (*GradeRunResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{12}
}

func (x *GradeRunResponse) GetCode() *CodeGradeResult {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *GradeRunResponse) GetProcess() *ProcessGradeResult {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *GradeRunResponse) GetJudge() *JudgeGradeResult {
	if x != nil {
		return x.Judge
	}
	return nil
}

func (x *GradeRunResponse) GetAdherence() *SpecAdherenceResult {
	if x != nil {
		return x.Adherence
	}
	return nil
}

func (x *GradeRunResponse) GetCompositeScore() float32 {
	if x != nil {
		return x.CompositeScore
	}
	return 0
}

type CodeGradeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestPassRate   float32                `protobuf:"fixed32,1,opt,name=test_pass_rate,json=testPassRate,proto3" json:"test_pass_rate,omitempty"`
	TestPassCount  int32                  `protobuf:"varint,2,opt,name=test_pass_count,json=testPassCount,proto3" json:"test_pass_count,omitempty"`
	TestFailCount  int32                  `protobuf:"varint,3,opt,name=test_fail_count,json=testFailCount,proto3" json:"test_fail_count,omitempty"`
	LintScore      float32                `protobuf:"fixed32,4,opt,name=lint_score,json=lintScore,proto3" json:"lint_score,omitempty"`
	TypeCheckPass  bool                   `protobuf:"varint,5,opt,name=type_check_pass,json=typeCheckPass,proto3" json:"type_check_pass,omitempty"`
	FileStateValid bool                   `protobuf:"varint,6,opt,name=file_state_valid,json=fileStateValid,proto3" json:"file_state_valid,omitempty"`
	TestResults    []*TestResult          `protobuf:"bytes,7,rep,name=test_results,json=testResults,proto3" json:"test_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeGradeResult) Reset() {
	*x = CodeGradeResult{}
	mi := &file_grader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeGradeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeGradeResult) ProtoMessage() {}

func (x *CodeGradeResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeGradeResult.ProtoReflect.Descriptor instead.
func (*CodeGradeResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{13}
}

func (x *CodeGradeResult) GetTestPassRate() float32 {
	if x != nil {
		return x.TestPassRate
	}
	return 0
}

func (x *CodeGradeResult) GetTestPassCount() int32 {
	if x != nil {
		return x.TestPassCount
	}
	return 0
}

func (x *CodeGradeResult) GetTestFailCount() int32 {
	if x != nil {
		return x.TestFailCount
	}
	return 0
}

func (x *CodeGradeResult) GetLintScore() float32 {
	if x != nil {
		return x.LintScore
	}
	return 0
}

func (x *CodeGradeResult) GetTypeCheckPass() bool {
	if x != nil {
		return x.TypeCheckPass
	}
	return false
}

func (x *CodeGradeResult) GetFileStateValid() bool {
	if x != nil {
		return x.FileStateValid
	}
	return false
}

func (x *CodeGradeResult) GetTestResults() []*TestResult {
	if x != nil {
		return x.TestResults
	}
	return nil
}

type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_grader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{14}
}

func (x *TestResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ProcessGradeResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TurnCount           int32                  `protobuf:"varint,1,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	TotalTokens         int32                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CostUsd             float32                `protobuf:"fixed32,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	TokenEfficiency     float32                `protobuf:"fixed32,4,opt,name=token_efficiency,json=tokenEfficiency,proto3" json:"token_efficiency,omitempty"`
	BacktrackCount      int32                  `protobuf:"varint,5,opt,name=backtrack_count,json=backtrackCount,proto3" json:"backtrack_count,omitempty"`
	SelfValidationRate  float32                `protobuf:"fixed32,6,opt,name=self_validation_rate,json=selfValidationRate,proto3" json:"self_validation_rate,omitempty"`
	PrematureCompletion bool                   `protobuf:"varint,7,opt,name=premature_completion,json=prematureCompletion,proto3" json:"premature_completion,omitempty"`
	IdleTurns           int32                  `protobuf:"varint,8,opt,name=idle_turns,json=idleTurns,proto3" json:"idle_turns,omitempty"`
	ErrorRecoveryCount  int32                  `protobuf:"varint,9,opt,name=error_recovery_count,json=errorRecoveryCount,proto3" json:"error_recovery_count,omitempty"`
	ToolCallAccuracy    float32                `protobuf:"fixed32,10,opt,name=tool_call_accuracy,json=toolCallAccuracy,proto3" json:"tool_call_accuracy,omitempty"`
	ContextUtilization  float32                `protobuf:"fixed32,11,opt,name=context_utilization,json=contextUtilization,proto3" json:"context_utilization,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessGradeResult) Reset() {
	*x = ProcessGradeResult{}
	mi := &file_grader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGradeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGradeResult) ProtoMessage() {}

func (x *ProcessGradeResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGradeResult.ProtoReflect.Descriptor instead.
func (*ProcessGradeResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessGradeResult) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *ProcessGradeResult) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ProcessGradeResult) GetCostUsd() float32 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *ProcessGradeResult) GetTokenEfficiency() float32 {
	if x != nil {
		return x.TokenEfficiency
	}
	return 0
}

func (x *ProcessGradeResult) GetBacktrackCount() int32 {
	if x != nil {
		return x.BacktrackCount
	}
	return 0
}

func (x *ProcessGradeResult) GetSelfValidationRate() float32 {
	if x != nil {
		return x.SelfValidationRate
	}
	return 0
}

func (x *ProcessGradeResult) GetPrematureCompletion() bool {
	if x != nil {
		return x.PrematureCompletion
	}
	return false
}

func (x *ProcessGradeResult) GetIdleTurns() int32 {
	if x != nil {
		return x.IdleTurns
	}
	return 0
}

func (x *ProcessGradeResult) GetErrorRecoveryCount() int32 {
	if x != nil {
		return x.ErrorRecoveryCount
	}
	return 0
}

func (x *ProcessGradeResult) GetToolCallAccuracy() float32 {
	if x != nil {
		return x.ToolCallAccuracy
	}
	return 0
}

func (x *ProcessGradeResult) GetContextUtilization() float32 {
	if x != nil {
		return x.ContextUtilization
	}
	return 0
}

type JudgeGradeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        map[string]float64     `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Rationales    map[string]string      `protobuf:"bytes,2,rep,name=rationales,proto3" json:"rationales,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IrrAlpha      float64                `protobuf:"fixed64,3,opt,name=irr_alpha,json=irrAlpha,proto3" json:"irr_alpha,omitempty"`
	RawResponses  []string               `protobuf:"bytes,4,rep,name=raw_responses,json=rawResponses,proto3" json:"raw_responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeGradeResult) Reset() {
	*x = JudgeGradeResult{}
	mi := &file_grader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeGradeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeGradeResult) ProtoMessage() {}

func (x *JudgeGradeResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeGradeResult.ProtoReflect.Descriptor instead.
func (*JudgeGradeResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{16}
}

func (x *JudgeGradeResult) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *JudgeGradeResult) GetRationales() map[string]string {
	if x != nil {
		return x.Rationales
	}
	return nil
}

func (x *JudgeGradeResult) GetIrrAlpha() float64 {
	if x != nil {
		return x.IrrAlpha
	}
	return 0
}

func (x *JudgeGradeResult) GetRawResponses() []string {
	if x != nil {
		return x.RawResponses
	}
	return nil
}

type SpecAdherenceResult struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	InstructionCompliance float32                `protobuf:"fixed32,1,opt,name=instruction_compliance,json=instructionCompliance,proto3" json:"instruction_compliance,omitempty"`
	ConstraintViolations  int32                  `protobuf:"varint,2,opt,name=constraint_violations,json=constraintViolations,proto3" json:"constraint_violations,omitempty"`
	ConventionAdherence   float32                `protobuf:"fixed32,3,opt,name=convention_adherence,json=conventionAdherence,proto3" json:"convention_adherence,omitempty"`
	PerInstruction        []*InstructionResult   `protobuf:"bytes,4,rep,name=per_instruction,json=perInstruction,proto3" json:"per_instruction,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SpecAdherenceResult) Reset() {
	*x = SpecAdherenceResult{}
	mi := &file_grader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecAdherenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecAdherenceResult) ProtoMessage() {}

func (x *SpecAdherenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecAdherenceResult.ProtoReflect.Descriptor instead.
func (*SpecAdherenceResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{17}
}

func (x *SpecAdherenceResult) GetInstructionCompliance() float32 {
	if x != nil {
		return x.InstructionCompliance
	}
	return 0
}

func (x *SpecAdherenceResult) GetConstraintViolations() int32 {
	if x != nil {
		return x.ConstraintViolations
	}
	return 0
}

func (x *SpecAdherenceResult) GetConventionAdherence() float32 {
	if x != nil {
		return x.ConventionAdherence
	}
	return 0
}

func (x *SpecAdherenceResult) GetPerInstruction() []*InstructionResult {
	if x != nil {
		return x.PerInstruction
	}
	return nil
}

type InstructionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   string                 `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reasoning     string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionResult) Reset() {
	*x = InstructionResult{}
	mi := &file_grader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionResult) ProtoMessage() {}

func (x *InstructionResult) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionResult.ProtoReflect.Descriptor instead.
func (*InstructionResult) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{18}
}

func (x *InstructionResult) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *InstructionResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstructionResult) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

type ComputeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId  string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	VariantGrades []*VariantGrades       `protobuf:"bytes,2,rep,name=variant_grades,json=variantGrades,proto3" json:"variant_grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeStatsRequest) Reset() {
	*x = ComputeStatsRequest{}
	mi := &file_grader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeStatsRequest) ProtoMessage() {}

func (x *ComputeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeStatsRequest.ProtoReflect.Descriptor instead.
func (*ComputeStatsRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{19}
}

func (x *ComputeStatsRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ComputeStatsRequest) GetVariantGrades() []*VariantGrades {
	if x != nil {
		return x.VariantGrades
	}
	return nil
}

type VariantGrades struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Grades        []*GradeRunResponse    `protobuf:"bytes,2,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantGrades) Reset() {
	*x = VariantGrades{}
	mi := &file_grader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantGrades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantGrades) ProtoMessage() {}

func (x *VariantGrades) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantGrades.ProtoReflect.Descriptor instead.
func (*VariantGrades) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{20}
}

func (x *VariantGrades) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *VariantGrades) GetGrades() []*GradeRunResponse {
	if x != nil {
		return x.Grades
	}
	return nil
}

type ComputeStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*PairwiseStat        `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeStatsResponse) Reset() {
	*x = ComputeStatsResponse{}
	mi := &file_grader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeStatsResponse) ProtoMessage() {}

func (x *ComputeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeStatsResponse.ProtoReflect.Descriptor instead.
func (*ComputeStatsResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{21}
}

func (x *ComputeStatsResponse) GetStats() []*PairwiseStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type PairwiseStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantAId    string                 `protobuf:"bytes,1,opt,name=variant_a_id,json=variantAId,proto3" json:"variant_a_id,omitempty"`
	VariantBId    string                 `protobuf:"bytes,2,opt,name=variant_b_id,json=variantBId,proto3" json:"variant_b_id,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MeanA         float32                `protobuf:"fixed32,4,opt,name=mean_a,json=meanA,proto3" json:"mean_a,omitempty"`
	MeanB         float32                `protobuf:"fixed32,5,opt,name=mean_b,json=meanB,proto3" json:"mean_b,omitempty"`
	MedianA       float32                `protobuf:"fixed32,6,opt,name=median_a,json=medianA,proto3" json:"median_a,omitempty"`
	MedianB       float32                `protobuf:"fixed32,7,opt,name=median_b,json=medianB,proto3" json:"median_b,omitempty"`
	StdA          float32                `protobuf:"fixed32,8,opt,name=std_a,json=stdA,proto3" json:"std_a,omitempty"`
	StdB          float32                `protobuf:"fixed32,9,opt,name=std_b,json=stdB,proto3" json:"std_b,omitempty"`
	MannWhitneyU  float32                `protobuf:"fixed32,10,opt,name=mann_whitney_u,json=mannWhitneyU,proto3" json:"mann_whitney_u,omitempty"`
	PValue        float32                `protobuf:"fixed32,11,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	CohensD       float32                `protobuf:"fixed32,12,opt,name=cohens_d,json=cohensD,proto3" json:"cohens_d,omitempty"`
	CiLower       float32                `protobuf:"fixed32,13,opt,name=ci_lower,json=ciLower,proto3" json:"ci_lower,omitempty"`
	CiUpper       float32                `protobuf:"fixed32,14,opt,name=ci_upper,json=ciUpper,proto3" json:"ci_upper,omitempty"`
	IsSignificant bool                   `protobuf:"varint,15,opt,name=is_significant,json=isSignificant,proto3" json:"is_significant,omitempty"`
	ObservedPower float32                `protobuf:"fixed32,16,opt,name=observed_power,json=observedPower,proto3" json:"observed_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairwiseStat) Reset() {
	*x = PairwiseStat{}
	mi := &file_grader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairwiseStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairwiseStat) ProtoMessage() {}

func (x *PairwiseStat) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairwiseStat.ProtoReflect.Descriptor instead.
func (*PairwiseStat) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{22}
}

func (x *PairwiseStat) GetVariantAId() string {
	if x != nil {
		return x.VariantAId
	}
	return ""
}

func (x *PairwiseStat) GetVariantBId() string {
	if x != nil {
		return x.VariantBId
	}
	return ""
}

func (x *PairwiseStat) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *PairwiseStat) GetMeanA() float32 {
	if x != nil {
		return x.MeanA
	}
	return 0
}

func (x *PairwiseStat) GetMeanB() float32 {
	if x != nil {
		return x.MeanB
	}
	return 0
}

func (x *PairwiseStat) GetMedianA() float32 {
	if x != nil {
		return x.MedianA
	}
	return 0
}

func (x *PairwiseStat) GetMedianB() float32 {
	if x != nil {
		return x.MedianB
	}
	return 0
}

func (x *PairwiseStat) GetStdA() float32 {
	if x != nil {
		return x.StdA
	}
	return 0
}

func (x *PairwiseStat) GetStdB() float32 {
	if x != nil {
		return x.StdB
	}
	return 0
}

func (x *PairwiseStat) GetMannWhitneyU() float32 {
	if x != nil {
		return x.MannWhitneyU
	}
	return 0
}

func (x *PairwiseStat) GetPValue() float32 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *PairwiseStat) GetCohensD() float32 {
	if x != nil {
		return x.CohensD
	}
	return 0
}

func (x *PairwiseStat) GetCiLower() float32 {
	if x != nil {
		return x.CiLower
	}
	return 0
}

func (x *PairwiseStat) GetCiUpper() float32 {
	if x != nil {
		return x.CiUpper
	}
	return 0
}

func (x *PairwiseStat) GetIsSignificant() bool {
	if x != nil {
		return x.IsSignificant
	}
	return false
}

func (x *PairwiseStat) GetObservedPower() float32 {
	if x != nil {
		return x.ObservedPower
	}
	return 0
}

type ClassifyDimensionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ArtifactType  string                 `protobuf:"bytes,2,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyDimensionsRequest) Reset() {
	*x = ClassifyDimensionsRequest{}
	mi := &file_grader_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyDimensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyDimensionsRequest) ProtoMessage() {}

func (x *ClassifyDimensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyDimensionsRequest.ProtoReflect.Descriptor instead.
func (*ClassifyDimensionsRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{23}
}

func (x *ClassifyDimensionsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClassifyDimensionsRequest) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ClassifyDimensionsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ClassifyDimensionsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ClassifyDimensionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Framing           string                 `protobuf:"bytes,1,opt,name=framing,proto3" json:"framing,omitempty"`
	Specificity       string                 `protobuf:"bytes,2,opt,name=specificity,proto3" json:"specificity,omitempty"`
	Structure         string                 `protobuf:"bytes,3,opt,name=structure,proto3" json:"structure,omitempty"`
	Scope             string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Tone              string                 `protobuf:"bytes,5,opt,name=tone,proto3" json:"tone,omitempty"`
	ConstraintDensity float32                `protobuf:"fixed32,6,opt,name=constraint_density,json=constraintDensity,proto3" json:"constraint_density,omitempty"`
	ExamplePresence   string                 `protobuf:"bytes,7,opt,name=example_presence,json=examplePresence,proto3" json:"example_presence,omitempty"`
	PrioritySignaling string                 `protobuf:"bytes,8,opt,name=priority_signaling,json=prioritySignaling,proto3" json:"priority_signaling,omitempty"`
	ToolGuidance      string                 `protobuf:"bytes,9,opt,name=tool_guidance,json=toolGuidance,proto3" json:"tool_guidance,omitempty"`
	ErrorHandling     string                 `protobuf:"bytes,10,opt,name=error_handling,json=errorHandling,proto3" json:"error_handling,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassifyDimensionsResponse) Reset() {
	*x = ClassifyDimensionsResponse{}
	mi := &file_grader_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyDimensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyDimensionsResponse) ProtoMessage() {}

func (x *ClassifyDimensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyDimensionsResponse.ProtoReflect.Descriptor instead.
func (*ClassifyDimensionsResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{24}
}

func (x *ClassifyDimensionsResponse) GetFraming() string {
	if x != nil {
		return x.Framing
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetSpecificity() string {
	if x != nil {
		return x.Specificity
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetStructure() string {
	if x != nil {
		return x.Structure
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetConstraintDensity() float32 {
	if x != nil {
		return x.ConstraintDensity
	}
	return 0
}

func (x *ClassifyDimensionsResponse) GetExamplePresence() string {
	if x != nil {
		return x.ExamplePresence
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetPrioritySignaling() string {
	if x != nil {
		return x.PrioritySignaling
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetToolGuidance() string {
	if x != nil {
		return x.ToolGuidance
	}
	return ""
}

func (x *ClassifyDimensionsResponse) GetErrorHandling() string {
	if x != nil {
		return x.ErrorHandling
	}
	return ""
}

// AgentDx failure classifier RPC. Story #22 owns the Python implementation;
// this proto carries the call from the Go orchestrator across the boundary.
//
// symptoms_json is the already-compact Symptoms packet serialized by the
// engine-side symptom extractor (Story #20). transcript_tail is the last
// N turns of the run formatted as `[<idx>][<role>] <content>` per line.
type ClassifyFailureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SymptomsJson    []byte                 `protobuf:"bytes,2,opt,name=symptoms_json,json=symptomsJson,proto3" json:"symptoms_json,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	TranscriptTail  string                 `protobuf:"bytes,4,opt,name=transcript_tail,json=transcriptTail,proto3" json:"transcript_tail,omitempty"`
	// Optional override for the classifier model id. Empty string uses the
	// server-side default (Claude Haiku 4.5 per spec §4.7.4).
	ClassifierModel string `protobuf:"bytes,5,opt,name=classifier_model,json=classifierModel,proto3" json:"classifier_model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClassifyFailureRequest) Reset() {
	*x = ClassifyFailureRequest{}
	mi := &file_grader_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyFailureRequest) ProtoMessage() {}

func (x *ClassifyFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyFailureRequest.ProtoReflect.Descriptor instead.
func (*ClassifyFailureRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{25}
}

func (x *ClassifyFailureRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ClassifyFailureRequest) GetSymptomsJson() []byte {
	if x != nil {
		return x.SymptomsJson
	}
	return nil
}

func (x *ClassifyFailureRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *ClassifyFailureRequest) GetTranscriptTail() string {
	if x != nil {
		return x.TranscriptTail
	}
	return ""
}

func (x *ClassifyFailureRequest) GetClassifierModel() string {
	if x != nil {
		return x.ClassifierModel
	}
	return ""
}

type ClassifyFailureResponse struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Classification *FailureClassificationProto `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
	// Total time spent inside the classifier (LLM call + retries). Useful
	// for surfacing per-run cost-vs-latency in the Diagnostic Compare view.
	LatencyMs     int32 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyFailureResponse) Reset() {
	*x = ClassifyFailureResponse{}
	mi := &file_grader_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyFailureResponse) ProtoMessage() {}

func (x *ClassifyFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyFailureResponse.ProtoReflect.Descriptor instead.
func (*ClassifyFailureResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{26}
}

func (x *ClassifyFailureResponse) GetClassification() *FailureClassificationProto {
	if x != nil {
		return x.Classification
	}
	return nil
}

func (x *ClassifyFailureResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type FailureClassificationProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FailureCode enum values are passed as strings to keep the proto stable
	// when the Python taxonomy grows without requiring a proto regen.
	Primary       string               `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary     []string             `protobuf:"bytes,2,rep,name=secondary,proto3" json:"secondary,omitempty"`
	Evidence      []*EvidenceSpanProto `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Confidence    float64              `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Rationale     string               `protobuf:"bytes,5,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureClassificationProto) Reset() {
	*x = FailureClassificationProto{}
	mi := &file_grader_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureClassificationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureClassificationProto) ProtoMessage() {}

func (x *FailureClassificationProto) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureClassificationProto.ProtoReflect.Descriptor instead.
func (*FailureClassificationProto) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{27}
}

func (x *FailureClassificationProto) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *FailureClassificationProto) GetSecondary() []string {
	if x != nil {
		return x.Secondary
	}
	return nil
}

func (x *FailureClassificationProto) GetEvidence() []*EvidenceSpanProto {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *FailureClassificationProto) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FailureClassificationProto) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type EvidenceSpanProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	TurnIndex     int32                  `protobuf:"varint,3,opt,name=turn_index,json=turnIndex,proto3" json:"turn_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceSpanProto) Reset() {
	*x = EvidenceSpanProto{}
	mi := &file_grader_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceSpanProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceSpanProto) ProtoMessage() {}

func (x *EvidenceSpanProto) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceSpanProto.ProtoReflect.Descriptor instead.
func (*EvidenceSpanProto) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{28}
}

func (x *EvidenceSpanProto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EvidenceSpanProto) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *EvidenceSpanProto) GetTurnIndex() int32 {
	if x != nil {
		return x.TurnIndex
	}
	return 0
}

var File_grader_proto protoreflect.FileDescriptor

const file_grader_proto_rawDesc = "" +
	"\n" +
	"\fgrader.proto\x12\x0fframeval.grader\"\a\n" +
	"\x05Empty\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xbf\x03\n" +
	"\x0fGradeRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0ftranscript_json\x18\x02 \x01(\tR\x0etranscriptJson\x12>\n" +
	"\foutput_files\x18\x03 \x03(\v2\x1b.frameval.grader.OutputFileR\voutputFiles\x12'\n" +
	"\x0ffilesystem_diff\x18\x04 \x01(\tR\x0efilesystemDiff\x12-\n" +
	"\x04task\x18\x05 \x01(\v2\x19.frameval.grader.TaskSpecR\x04task\x129\n" +
	"\bartifact\x18\x06 \x01(\v2\x1d.frameval.grader.ArtifactSpecR\bartifact\x12?\n" +
	"\fjudge_config\x18\a \x01(\v2\x1c.frameval.grader.JudgeConfigR\vjudgeConfig\x12X\n" +
	"\x15verified_test_results\x18\b \x01(\v2$.frameval.grader.VerifiedTestResultsR\x13verifiedTestResults\"\x92\x01\n" +
	"\x13VerifiedTestResults\x12\x1d\n" +
	"\n" +
	"pass_count\x18\x01 \x01(\x05R\tpassCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x02 \x01(\x05R\tfailCount\x12=\n" +
	"\aresults\x18\x03 \x03(\v2#.frameval.grader.VerifiedTestResultR\aresults\"X\n" +
	"\x12VerifiedTestResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\":\n" +
	"\n" +
	"OutputFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xb4\x01\n" +
	"\bTaskSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12#\n" +
	"\rcodebase_type\x18\x03 \x01(\tR\fcodebaseType\x128\n" +
	"\n" +
	"test_cases\x18\x04 \x03(\v2\x19.frameval.grader.TestCaseR\ttestCases\x12!\n" +
	"\fsetup_script\x18\x05 \x01(\tR\vsetupScript\"a\n" +
	"\bTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0fexpected_result\x18\x03 \x01(\tR\x0eexpectedResult\"<\n" +
	"\fArtifactSpec\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\";\n" +
	"\x0fDimensionRubric\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"\xf1\x01\n" +
	"\vJudgeConfig\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x128\n" +
	"\x06rubric\x18\x04 \x03(\v2 .frameval.grader.RubricDimensionR\x06rubric\x12!\n" +
	"\fjudge_rounds\x18\x05 \x01(\x05R\vjudgeRounds\x12:\n" +
	"\arubrics\x18\x06 \x03(\v2 .frameval.grader.DimensionRubricR\arubrics\"{\n" +
	"\x0fRubricDimension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcriteria\x18\x02 \x01(\tR\bcriteria\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x05R\bminScore\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\"\xad\x02\n" +
	"\x10GradeRunResponse\x124\n" +
	"\x04code\x18\x01 \x01(\v2 .frameval.grader.CodeGradeResultR\x04code\x12=\n" +
	"\aprocess\x18\x02 \x01(\v2#.frameval.grader.ProcessGradeResultR\aprocess\x127\n" +
	"\x05judge\x18\x03 \x01(\v2!.frameval.grader.JudgeGradeResultR\x05judge\x12B\n" +
	"\tadherence\x18\x04 \x01(\v2$.frameval.grader.SpecAdherenceResultR\tadherence\x12'\n" +
	"\x0fcomposite_score\x18\x05 \x01(\x02R\x0ecompositeScore\"\xb8\x02\n" +
	"\x0fCodeGradeResult\x12$\n" +
	"\x0etest_pass_rate\x18\x01 \x01(\x02R\ftestPassRate\x12&\n" +
	"\x0ftest_pass_count\x18\x02 \x01(\x05R\rtestPassCount\x12&\n" +
	"\x0ftest_fail_count\x18\x03 \x01(\x05R\rtestFailCount\x12\x1d\n" +
	"\n" +
	"lint_score\x18\x04 \x01(\x02R\tlintScore\x12&\n" +
	"\x0ftype_check_pass\x18\x05 \x01(\bR\rtypeCheckPass\x12(\n" +
	"\x10file_state_valid\x18\x06 \x01(\bR\x0efileStateValid\x12>\n" +
	"\ftest_results\x18\a \x03(\v2\x1b.frameval.grader.TestResultR\vtestResults\"P\n" +
	"\n" +
	"TestResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"\xda\x03\n" +
	"\x12ProcessGradeResult\x12\x1d\n" +
	"\n" +
	"turn_count\x18\x01 \x01(\x05R\tturnCount\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x05R\vtotalTokens\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x02R\acostUsd\x12)\n" +
	"\x10token_efficiency\x18\x04 \x01(\x02R\x0ftokenEfficiency\x12'\n" +
	"\x0fbacktrack_count\x18\x05 \x01(\x05R\x0ebacktrackCount\x120\n" +
	"\x14self_validation_rate\x18\x06 \x01(\x02R\x12selfValidationRate\x121\n" +
	"\x14premature_completion\x18\a \x01(\bR\x13prematureCompletion\x12\x1d\n" +
	"\n" +
	"idle_turns\x18\b \x01(\x05R\tidleTurns\x120\n" +
	"\x14error_recovery_count\x18\t \x01(\x05R\x12errorRecoveryCount\x12,\n" +
	"\x12tool_call_accuracy\x18\n" +
	" \x01(\x02R\x10toolCallAccuracy\x12/\n" +
	"\x13context_utilization\x18\v \x01(\x02R\x12contextUtilization\"\xe8\x02\n" +
	"\x10JudgeGradeResult\x12E\n" +
	"\x06scores\x18\x01 \x03(\v2-.frameval.grader.JudgeGradeResult.ScoresEntryR\x06scores\x12Q\n" +
	"\n" +
	"rationales\x18\x02 \x03(\v21.frameval.grader.JudgeGradeResult.RationalesEntryR\n" +
	"rationales\x12\x1b\n" +
	"\tirr_alpha\x18\x03 \x01(\x01R\birrAlpha\x12#\n" +
	"\rraw_responses\x18\x04 \x03(\tR\frawResponses\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fRationalesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x13SpecAdherenceResult\x125\n" +
	"\x16instruction_compliance\x18\x01 \x01(\x02R\x15instructionCompliance\x123\n" +
	"\x15constraint_violations\x18\x02 \x01(\x05R\x14constraintViolations\x121\n" +
	"\x14convention_adherence\x18\x03 \x01(\x02R\x13conventionAdherence\x12K\n" +
	"\x0fper_instruction\x18\x04 \x03(\v2\".frameval.grader.InstructionResultR\x0eperInstruction\"k\n" +
	"\x11InstructionResult\x12 \n" +
	"\vinstruction\x18\x01 \x01(\tR\vinstruction\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\"\x81\x01\n" +
	"\x13ComputeStatsRequest\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x12E\n" +
	"\x0evariant_grades\x18\x02 \x03(\v2\x1e.frameval.grader.VariantGradesR\rvariantGrades\"i\n" +
	"\rVariantGrades\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tR\tvariantId\x129\n" +
	"\x06grades\x18\x02 \x03(\v2!.frameval.grader.GradeRunResponseR\x06grades\"K\n" +
	"\x14ComputeStatsResponse\x123\n" +
	"\x05stats\x18\x01 \x03(\v2\x1d.frameval.grader.PairwiseStatR\x05stats\"\xdf\x03\n" +
	"\fPairwiseStat\x12 \n" +
	"\fvariant_a_id\x18\x01 \x01(\tR\n" +
	"variantAId\x12 \n" +
	"\fvariant_b_id\x18\x02 \x01(\tR\n" +
	"variantBId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x15\n" +
	"\x06mean_a\x18\x04 \x01(\x02R\x05meanA\x12\x15\n" +
	"\x06mean_b\x18\x05 \x01(\x02R\x05meanB\x12\x19\n" +
	"\bmedian_a\x18\x06 \x01(\x02R\amedianA\x12\x19\n" +
	"\bmedian_b\x18\a \x01(\x02R\amedianB\x12\x13\n" +
	"\x05std_a\x18\b \x01(\x02R\x04stdA\x12\x13\n" +
	"\x05std_b\x18\t \x01(\x02R\x04stdB\x12$\n" +
	"\x0emann_whitney_u\x18\n" +
	" \x01(\x02R\fmannWhitneyU\x12\x17\n" +
	"\ap_value\x18\v \x01(\x02R\x06pValue\x12\x19\n" +
	"\bcohens_d\x18\f \x01(\x02R\acohensD\x12\x19\n" +
	"\bci_lower\x18\r \x01(\x02R\aciLower\x12\x19\n" +
	"\bci_upper\x18\x0e \x01(\x02R\aciUpper\x12%\n" +
	"\x0eis_significant\x18\x0f \x01(\bR\risSignificant\x12%\n" +
	"\x0eobserved_power\x18\x10 \x01(\x02R\robservedPower\"\x89\x01\n" +
	"\x19ClassifyDimensionsRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rartifact_type\x18\x02 \x01(\tR\fartifactType\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"\xf5\x02\n" +
	"\x1aClassifyDimensionsResponse\x12\x18\n" +
	"\aframing\x18\x01 \x01(\tR\aframing\x12 \n" +
	"\vspecificity\x18\x02 \x01(\tR\vspecificity\x12\x1c\n" +
	"\tstructure\x18\x03 \x01(\tR\tstructure\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x12\n" +
	"\x04tone\x18\x05 \x01(\tR\x04tone\x12-\n" +
	"\x12constraint_density\x18\x06 \x01(\x02R\x11constraintDensity\x12)\n" +
	"\x10example_presence\x18\a \x01(\tR\x0fexamplePresence\x12-\n" +
	"\x12priority_signaling\x18\b \x01(\tR\x11prioritySignaling\x12#\n" +
	"\rtool_guidance\x18\t \x01(\tR\ftoolGuidance\x12%\n" +
	"\x0eerror_handling\x18\n" +
	" \x01(\tR\rerrorHandling\"\xd3\x01\n" +
	"\x16ClassifyFailureRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rsymptoms_json\x18\x02 \x01(\fR\fsymptomsJson\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12'\n" +
	"\x0ftranscript_tail\x18\x04 \x01(\tR\x0etranscriptTail\x12)\n" +
	"\x10classifier_model\x18\x05 \x01(\tR\x0fclassifierModel\"\x8d\x01\n" +
	"\x17ClassifyFailureResponse\x12S\n" +
	"\x0eclassification\x18\x01 \x01(\v2+.frameval.grader.FailureClassificationProtoR\x0eclassification\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x05R\tlatencyMs\"\xd2\x01\n" +
	"\x1aFailureClassificationProto\x12\x18\n" +
	"\aprimary\x18\x01 \x01(\tR\aprimary\x12\x1c\n" +
	"\tsecondary\x18\x02 \x03(\tR\tsecondary\x12>\n" +
	"\bevidence\x18\x03 \x03(\v2\".frameval.grader.EvidenceSpanProtoR\bevidence\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\trationale\x18\x05 \x01(\tR\trationale\"\\\n" +
	"\x11EvidenceSpanProto\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x12\x1d\n" +
	"\n" +
	"turn_index\x18\x03 \x01(\x05R\tturnIndex2\xda\x03\n" +
	"\rGraderService\x12O\n" +
	"\bGradeRun\x12 .frameval.grader.GradeRunRequest\x1a!.frameval.grader.GradeRunResponse\x12[\n" +
	"\fComputeStats\x12$.frameval.grader.ComputeStatsRequest\x1a%.frameval.grader.ComputeStatsResponse\x12m\n" +
	"\x12ClassifyDimensions\x12*.frameval.grader.ClassifyDimensionsRequest\x1a+.frameval.grader.ClassifyDimensionsResponse\x12d\n" +
	"\x0fClassifyFailure\x12'.frameval.grader.ClassifyFailureRequest\x1a(.frameval.grader.ClassifyFailureResponse\x12F\n" +
	"\vHealthCheck\x12\x16.frameval.grader.Empty\x1a\x1f.frameval.grader.HealthResponseB9Z7github.com/mustafaselman/frameval/engine/proto;graderpbb\x06proto3"

var (
	file_grader_proto_rawDescOnce sync.Once
	file_grader_proto_rawDescData []byte
)

func file_grader_proto_rawDescGZIP() []byte {
	file_grader_proto_rawDescOnce.Do(func() {
		file_grader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grader_proto_rawDesc), len(file_grader_proto_rawDesc)))
	})
	return file_grader_proto_rawDescData
}

var file_grader_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_grader_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: frameval.grader.Empty
	(*HealthResponse)(nil),             // 1: frameval.grader.HealthResponse
	(*GradeRunRequest)(nil),            // 2: frameval.grader.GradeRunRequest
	(*VerifiedTestResults)(nil),        // 3: frameval.grader.VerifiedTestResults
	(*VerifiedTestResult)(nil),         // 4: frameval.grader.VerifiedTestResult
	(*OutputFile)(nil),                 // 5: frameval.grader.OutputFile
	(*TaskSpec)(nil),                   // 6: frameval.grader.TaskSpec
	(*TestCase)(nil),                   // 7: frameval.grader.TestCase
	(*ArtifactSpec)(nil),               // 8: frameval.grader.ArtifactSpec
	(*DimensionRubric)(nil),            // 9: frameval.grader.DimensionRubric
	(*JudgeConfig)(nil),                // 10: frameval.grader.JudgeConfig
	(*RubricDimension)(nil),            // 11: frameval.grader.RubricDimension
	(*GradeRunResponse)(nil),           // 12: frameval.grader.GradeRunResponse
	(*CodeGradeResult)(nil),            // 13: frameval.grader.CodeGradeResult
	(*TestResult)(nil),                 // 14: frameval.grader.TestResult
	(*ProcessGradeResult)(nil),         // 15: frameval.grader.ProcessGradeResult
	(*JudgeGradeResult)(nil),           // 16: frameval.grader.JudgeGradeResult
	(*SpecAdherenceResult)(nil),        // 17: frameval.grader.SpecAdherenceResult
	(*InstructionResult)(nil),          // 18: frameval.grader.InstructionResult
	(*ComputeStatsRequest)(nil),        // 19: frameval.grader.ComputeStatsRequest
	(*VariantGrades)(nil),              // 20: frameval.grader.VariantGrades
	(*ComputeStatsResponse)(nil),       // 21: frameval.grader.ComputeStatsResponse
	(*PairwiseStat)(nil),               // 22: frameval.grader.PairwiseStat
	(*ClassifyDimensionsRequest)(nil),  // 23: frameval.grader.ClassifyDimensionsRequest
	(*ClassifyDimensionsResponse)(nil), // 24: frameval.grader.ClassifyDimensionsResponse
	(*ClassifyFailureRequest)(nil),     // 25: frameval.grader.ClassifyFailureRequest
	(*ClassifyFailureResponse)(nil),    // 26: frameval.grader.ClassifyFailureResponse
	(*FailureClassificationProto)(nil), // 27: frameval.grader.FailureClassificationProto
	(*EvidenceSpanProto)(nil),          // 28: frameval.grader.EvidenceSpanProto
	nil,                                // 29: frameval.grader.JudgeGradeResult.ScoresEntry
	nil,                                // 30: frameval.grader.JudgeGradeResult.RationalesEntry
}
var file_grader_proto_depIdxs = []int32{
	5,  // 0: frameval.grader.GradeRunRequest.output_files:type_name -> frameval.grader.OutputFile
	6,  // 1: frameval.grader.GradeRunRequest.task:type_name -> frameval.grader.TaskSpec
	8,  // 2: frameval.grader.GradeRunRequest.artifact:type_name -> frameval.grader.ArtifactSpec
	10, // 3: frameval.grader.GradeRunRequest.judge_config:type_name -> frameval.grader.JudgeConfig
	3,  // 4: frameval.grader.GradeRunRequest.verified_test_results:type_name -> frameval.grader.VerifiedTestResults
	4,  // 5: frameval.grader.VerifiedTestResults.results:type_name -> frameval.grader.VerifiedTestResult
	7,  // 6: frameval.grader.TaskSpec.test_cases:type_name -> frameval.grader.TestCase
	11, // 7: frameval.grader.JudgeConfig.rubric:type_name -> frameval.grader.RubricDimension
	9,  // 8: frameval.grader.JudgeConfig.rubrics:type_name -> frameval.grader.DimensionRubric
	13, // 9: frameval.grader.GradeRunResponse.code:type_name -> frameval.grader.CodeGradeResult
	15, // 10: frameval.grader.GradeRunResponse.process:type_name -> frameval.grader.ProcessGradeResult
	16, // 11: frameval.grader.GradeRunResponse.judge:type_name -> frameval.grader.JudgeGradeResult
	17, // 12: frameval.grader.GradeRunResponse.adherence:type_name -> frameval.grader.SpecAdherenceResult
	14, // 13: frameval.grader.CodeGradeResult.test_results:type_name -> frameval.grader.TestResult
	29, // 14: frameval.grader.JudgeGradeResult.scores:type_name -> frameval.grader.JudgeGradeResult.ScoresEntry
	30, // 15: frameval.grader.JudgeGradeResult.rationales:type_name -> frameval.grader.JudgeGradeResult.RationalesEntry
	18, // 16: frameval.grader.SpecAdherenceResult.per_instruction:type_name -> frameval.grader.InstructionResult
	20, // 17: frameval.grader.ComputeStatsRequest.variant_grades:type_name -> frameval.grader.VariantGrades
	12, // 18: frameval.grader.VariantGrades.grades:type_name -> frameval.grader.GradeRunResponse
	22, // 19: frameval.grader.ComputeStatsResponse.stats:type_name -> frameval.grader.PairwiseStat
	27, // 20: frameval.grader.ClassifyFailureResponse.classification:type_name -> frameval.grader.FailureClassificationProto
	28, // 21: frameval.grader.FailureClassificationProto.evidence:type_name -> frameval.grader.EvidenceSpanProto
	2,  // 22: frameval.grader.GraderService.GradeRun:input_type -> frameval.grader.GradeRunRequest
	19, // 23: frameval.grader.GraderService.ComputeStats:input_type -> frameval.grader.ComputeStatsRequest
	23, // 24: frameval.grader.GraderService.ClassifyDimensions:input_type -> frameval.grader.ClassifyDimensionsRequest
	25, // 25: frameval.grader.GraderService.ClassifyFailure:input_type -> frameval.grader.ClassifyFailureRequest
	0,  // 26: frameval.grader.GraderService.HealthCheck:input_type -> frameval.grader.Empty
	12, // 27: frameval.grader.GraderService.GradeRun:output_type -> frameval.grader.GradeRunResponse
	21, // 28: frameval.grader.GraderService.ComputeStats:output_type -> frameval.grader.ComputeStatsResponse
	24, // 29: frameval.grader.GraderService.ClassifyDimensions:output_type -> frameval.grader.ClassifyDimensionsResponse
	26, // 30: frameval.grader.GraderService.ClassifyFailure:output_type -> frameval.grader.ClassifyFailureResponse
	1,  // 31: frameval.grader.GraderService.HealthCheck:output_type -> frameval.grader.HealthResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_grader_proto_init() }
func file_grader_proto_init() {
	if File_grader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grader_proto_rawDesc), len(file_grader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grader_proto_goTypes,
		DependencyIndexes: file_grader_proto_depIdxs,
		MessageInfos:      file_grader_proto_msgTypes,
	}.Build()
	File_grader_proto = out.File
	file_grader_proto_goTypes = nil
	file_grader_proto_depIdxs = nil
}
