// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: grader.proto

package graderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraderService_GradeRun_FullMethodName           = "/frameval.grader.GraderService/GradeRun"
	GraderService_ComputeStats_FullMethodName       = "/frameval.grader.GraderService/ComputeStats"
	GraderService_ClassifyDimensions_FullMethodName = "/frameval.grader.GraderService/ClassifyDimensions"
	GraderService_ClassifyFailure_FullMethodName    = "/frameval.grader.GraderService/ClassifyFailure"
	GraderService_HealthCheck_FullMethodName        = "/frameval.grader.GraderService/HealthCheck"
)

// GraderServiceClient is the client API for GraderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraderServiceClient interface {
	GradeRun(ctx context.Context, in *GradeRunRequest, opts ...grpc.CallOption) (*GradeRunResponse, error)
	ComputeStats(ctx context.Context, in *ComputeStatsRequest, opts ...grpc.CallOption) (*ComputeStatsResponse, error)
	ClassifyDimensions(ctx context.Context, in *ClassifyDimensionsRequest, opts ...grpc.CallOption) (*ClassifyDimensionsResponse, error)
	ClassifyFailure(ctx context.Context, in *ClassifyFailureRequest, opts ...grpc.CallOption) (*ClassifyFailureResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type graderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraderServiceClient(cc grpc.ClientConnInterface) GraderServiceClient {
	return &graderServiceClient{cc}
}

func (c *graderServiceClient) GradeRun(ctx context.Context, in *GradeRunRequest, opts ...grpc.CallOption) (*GradeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeRunResponse)
	err := c.cc.Invoke(ctx, GraderService_GradeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) ComputeStats(ctx context.Context, in *ComputeStatsRequest, opts ...grpc.CallOption) (*ComputeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeStatsResponse)
	err := c.cc.Invoke(ctx, GraderService_ComputeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) ClassifyDimensions(ctx context.Context, in *ClassifyDimensionsRequest, opts ...grpc.CallOption) (*ClassifyDimensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyDimensionsResponse)
	err := c.cc.Invoke(ctx, GraderService_ClassifyDimensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) ClassifyFailure(ctx context.Context, in *ClassifyFailureRequest, opts ...grpc.CallOption) (*ClassifyFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyFailureResponse)
	err := c.cc.Invoke(ctx, GraderService_ClassifyFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GraderService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderServiceServer is the server API for GraderService service.
// All implementations must embed UnimplementedGraderServiceServer
// for forward compatibility.
type GraderServiceServer interface {
	GradeRun(context.Context, *GradeRunRequest) (*GradeRunResponse, error)
	ComputeStats(context.Context, *ComputeStatsRequest) (*ComputeStatsResponse, error)
	ClassifyDimensions(context.Context, *ClassifyDimensionsRequest) (*ClassifyDimensionsResponse, error)
	ClassifyFailure(context.Context, *ClassifyFailureRequest) (*ClassifyFailureResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedGraderServiceServer()
}

// UnimplementedGraderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraderServiceServer struct{}

func (UnimplementedGraderServiceServer) GradeRun(context.Context, *GradeRunRequest) (*GradeRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeRun not implemented")
}
func (UnimplementedGraderServiceServer) ComputeStats(context.Context, *ComputeStatsRequest) (*ComputeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeStats not implemented")
}
func (UnimplementedGraderServiceServer) ClassifyDimensions(context.Context, *ClassifyDimensionsRequest) (*ClassifyDimensionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyDimensions not implemented")
}
func (UnimplementedGraderServiceServer) ClassifyFailure(context.Context, *ClassifyFailureRequest) (*ClassifyFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyFailure not implemented")
}
func (UnimplementedGraderServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGraderServiceServer) mustEmbedUnimplementedGraderServiceServer() {}
func (UnimplementedGraderServiceServer) testEmbeddedByValue()                       {}

// UnsafeGraderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraderServiceServer will
// result in compilation errors.
type UnsafeGraderServiceServer interface {
	mustEmbedUnimplementedGraderServiceServer()
}

func RegisterGraderServiceServer(s grpc.ServiceRegistrar, srv GraderServiceServer) {
	// If the following call panics, it indicates UnimplementedGraderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraderService_ServiceDesc, srv)
}

func _GraderService_GradeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).GradeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_GradeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).GradeRun(ctx, req.(*GradeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_ComputeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).ComputeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_ComputeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).ComputeStats(ctx, req.(*ComputeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_ClassifyDimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyDimensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).ClassifyDimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_ClassifyDimensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).ClassifyDimensions(ctx, req.(*ClassifyDimensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_ClassifyFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).ClassifyFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_ClassifyFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).ClassifyFailure(ctx, req.(*ClassifyFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraderService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraderService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GraderService_ServiceDesc is the grpc.ServiceDesc for GraderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frameval.grader.GraderService",
	HandlerType: (*GraderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GradeRun",
			Handler:    _GraderService_GradeRun_Handler,
		},
		{
			MethodName: "ComputeStats",
			Handler:    _GraderService_ComputeStats_Handler,
		},
		{
			MethodName: "ClassifyDimensions",
			Handler:    _GraderService_ClassifyDimensions_Handler,
		},
		{
			MethodName: "ClassifyFailure",
			Handler:    _GraderService_ClassifyFailure_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GraderService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grader.proto",
}
