# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grader_pb2 as grader__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GradeRun = channel.unary_unary(
                '/frameval.grader.GraderService/GradeRun',
                request_serializer=grader__pb2.GradeRunRequest.SerializeToString,
                response_deserializer=grader__pb2.GradeRunResponse.FromString,
                _registered_method=True)
        self.ComputeStats = channel.unary_unary(
                '/frameval.grader.GraderService/ComputeStats',
                request_serializer=grader__pb2.ComputeStatsRequest.SerializeToString,
                response_deserializer=grader__pb2.ComputeStatsResponse.FromString,
                _registered_method=True)
        self.ClassifyDimensions = channel.unary_unary(
                '/frameval.grader.GraderService/ClassifyDimensions',
                request_serializer=grader__pb2.ClassifyDimensionsRequest.SerializeToString,
                response_deserializer=grader__pb2.ClassifyDimensionsResponse.FromString,
                _registered_method=True)
        self.ClassifyFailure = channel.unary_unary(
                '/frameval.grader.GraderService/ClassifyFailure',
                request_serializer=grader__pb2.ClassifyFailureRequest.SerializeToString,
                response_deserializer=grader__pb2.ClassifyFailureResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/frameval.grader.GraderService/HealthCheck',
                request_serializer=grader__pb2.Empty.SerializeToString,
                response_deserializer=grader__pb2.HealthResponse.FromString,
                _registered_method=True)


class GraderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GradeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyDimensions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyFailure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GradeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeRun,
                    request_deserializer=grader__pb2.GradeRunRequest.FromString,
                    response_serializer=grader__pb2.GradeRunResponse.SerializeToString,
            ),
            'ComputeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeStats,
                    request_deserializer=grader__pb2.ComputeStatsRequest.FromString,
                    response_serializer=grader__pb2.ComputeStatsResponse.SerializeToString,
            ),
            'ClassifyDimensions': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDimensions,
                    request_deserializer=grader__pb2.ClassifyDimensionsRequest.FromString,
                    response_serializer=grader__pb2.ClassifyDimensionsResponse.SerializeToString,
            ),
            'ClassifyFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyFailure,
                    request_deserializer=grader__pb2.ClassifyFailureRequest.FromString,
                    response_serializer=grader__pb2.ClassifyFailureResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=grader__pb2.Empty.FromString,
                    response_serializer=grader__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frameval.grader.GraderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('frameval.grader.GraderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GradeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frameval.grader.GraderService/GradeRun',
            grader__pb2.GradeRunRequest.SerializeToString,
            grader__pb2.GradeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frameval.grader.GraderService/ComputeStats',
            grader__pb2.ComputeStatsRequest.SerializeToString,
            grader__pb2.ComputeStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyDimensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frameval.grader.GraderService/ClassifyDimensions',
            grader__pb2.ClassifyDimensionsRequest.SerializeToString,
            grader__pb2.ClassifyDimensionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frameval.grader.GraderService/ClassifyFailure',
            grader__pb2.ClassifyFailureRequest.SerializeToString,
            grader__pb2.ClassifyFailureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/frameval.grader.GraderService/HealthCheck',
            grader__pb2.Empty.SerializeToString,
            grader__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
